name: K8s Deploy Plugin
description: Deploys applications to a kubernetes cluster. Requires the agent to have kubectl and a valid config for your cluster
author: https://github.com/agworld
requirements: []
configuration:
  properties:
    action:
      type: string
      enum:
        - updateImage
        - promoteImage

    # updateImage options
    namespace:
      type: string
      default: default
    deploymentName:
      type: string
    containers:
      type: array
      items:
        type: object
        properties:
          image:
            type: string
          containerName:
            type: string
        required:
          - image
          - containerName
    patchJSON:
      type: string

    # promoteImage options
    sourceImage:
      description: "URL of the source repository i.e. www.mysourcerepo.com/myimage:latest"
      type: object
      properties:
        image: string
        repositoryUrl: string
        region: string
    destinationImages:
      description: "URLs of the destination repositories i.e. www.mydestinationrepo.com/myimage:latest"
      type: array
      items:
        type: object
        properties:
          image: string
          repositoryUrl: string
          region: string

    # common settings
    timeout:
      type: integer
      default: 300

  anyOf:
    - properties:
        action:
          const: updateImage
      required:
        - namespace
        - deploymentName
        - containers
    - properties:
        action:
          const: promoteImage
      required:
        - sourceImage
        - destinationImages

  additionalProperties: false
