name: K8s Deploy Plugin
description: Deploys applications to a kubernetes cluster. Requires the agent to have kubectl and a valid config for your cluster
author: https://github.com/agworld
requirements: []
configuration:
  properties:
    action:
      type: string
      enum:
        - updateImage
        - promoteImage
        - runJob

    # updateImage options
    deployments:
      type: array
      items:
        type: object
        properties:
          name: string
          namespace: string
          patches:
            type: array
            items:
              type: object
              properties:
                op: string
                path: string
                value: string
          containers:
            type: array
            items:
              type: object
              properties:
                image:
                  type: string
                containerName:
                  type: string
              required:
                - image
                - containerName

    # updateCronJob options
    cronjobs:
      type: array
      items:
        type: object
        properties:
          name: string
          namespace: string
          patches:
            type: array
            items:
              type: object
              properties:
                op: string
                path: string
                value: string
          containers:
            type: array
            items:
              type: object
              properties:
                image:
                  type: string
                containerName:
                  type: string
              required:
                - image
                - containerName

    # promoteImage options
    sourceImage:
      description: "URL of the source repository i.e. www.mysourcerepo.com/myimage:latest"
      type: object
      properties:
        image: string
        repositoryUrl: string
        region: string
    destinationImages:
      description: "URLs of the destination repositories i.e. www.mydestinationrepo.com/myimage:latest"
      type: array
      items:
        type: object
        properties:
          image: string
          repositoryUrl: string
          region: string

    # run job
    jobTemplateUrl:
      description: "The S3 url of the json template file i.e. s3://my-bucket-name/my_job_template.json "
      type: string
    jobImage:
      description: "URL of the job image i.e. www.mydestinationrepo.com/myimage:latest"
      type: string
    jobNamespace:
      description: "Kubernetes namespace where the job is to be created"
      type: string
      default: default

    # common settings
    timeout:
      type: integer
      default: 300

  anyOf:
    - properties:
        action:
          const: updateImage
      required:
        - deployments
    - properties:
        action:
          const: promoteImage
      required:
        - sourceImage
        - destinationImages
    - properties:
        action:
          const: runJob
      required:
        - jobTemplateUrl
        - jobImage

  additionalProperties: false
